version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 1234567890.dkr.ecr.us-west-2.amazonaws.com/flask-api-app-repo
  build:
    commands:
      - echo Building Docker image...
      - docker build -t my-app .
      - docker tag my-app:latest $ECR_URI:latest
  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $ECR_URI:latest
      - echo Build completed on `date`
