apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s-blue-green
  region: us-east-1
  version: "1.29"

vpc:
  subnets:
    public:
      k8s-blue-1a:
        id: subnet-XXXXXXXXXXXXXXXXX
      k8s-blue-1b:
        id: subnet-XXXXXXXXXXXXXXXXX
      k8s-blue-1c:
        id: subnet-XXXXXXXXXXXXXXXXX
      k8s-green-1a:
        id: subnet-XXXXXXXXXXXXXXXXX
      k8s-green-1b:
        id: subnet-XXXXXXXXXXXXXXXXX
      k8s-green-1c:
        id: subnet-XXXXXXXXXXXXXXXXX

managedNodeGroups:
  - name: k8s-blue-ng
    instanceType: t3.medium
    desiredCapacity: 3
    subnets:
      - subnet-XXXXXXXXXXXXXXXXX
      - subnet-XXXXXXXXXXXXXXXXX
      - subnet-XXXXXXXXXXXXXXXXX
    ssh:
      allow: true
      publicKeyName: XXXXXXXXXXXXXXXXXs
    tags:
      auto-delete: "no"
  - name: k8s-green-ng
    instanceType: t3.medium
    desiredCapacity: 3
    subnets:
      - subnet-XXXXXXXXXXXXXXXXX
      - subnet-XXXXXXXXXXXXXXXXX
      - subnet-XXXXXXXXXXXXXXXXX
    ssh:
      allow: true
      publicKeyName: XXXXXXXXXXXXXXXXX
    tags:
      auto-delete: "no"